#!/usr/bin/env bash
# Does the following:
#  Make a file called /var/run/myscript.pid inave the script PID.
#   Displays "To infinity and beyond" indefinitely
#   after gett a SIGT, displ "I hate the kill comm"
#   "Y U no love me?!" is disp after gett a SIGINT
#  terminates upon delet the file /var/run/myscriptpid
#+  receiving a SIGQUIT or SIGTERM.

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
