#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
#   On the 9th iteration, displays "Hi" before "Best School".

cou=0

while [ $cou -lt 10 ]
do
  if [ $cou -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( cou++ ))
done
